-- ConnectChat Pro Enterprise v5 collaboration migration
-- Run this entire file once in Supabase SQL Editor.

create table if not exists public.groups (
  id bigint generated by default as identity primary key,
  name text not null check (char_length(name) between 1 and 80),
  description text not null default '',
  avatar_url text,
  owner_id bigint not null references public.users(id) on delete cascade,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.group_members (
  group_id bigint not null references public.groups(id) on delete cascade,
  user_id bigint not null references public.users(id) on delete cascade,
  role text not null default 'member' check (role in ('owner','admin','member')),
  joined_at timestamptz not null default now(),
  primary key (group_id,user_id)
);

create table if not exists public.group_messages (
  id bigint generated by default as identity primary key,
  group_id bigint not null references public.groups(id) on delete cascade,
  sender_id bigint not null references public.users(id) on delete cascade,
  body text not null check (char_length(body) between 1 and 4000),
  created_at timestamptz not null default now()
);

create table if not exists public.channels (
  id bigint generated by default as identity primary key,
  name text not null check (char_length(name) between 1 and 80),
  description text not null default '',
  visibility text not null default 'private' check (visibility in ('public','private')),
  owner_id bigint not null references public.users(id) on delete cascade,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.channel_members (
  channel_id bigint not null references public.channels(id) on delete cascade,
  user_id bigint not null references public.users(id) on delete cascade,
  role text not null default 'member' check (role in ('owner','admin','member')),
  joined_at timestamptz not null default now(),
  primary key (channel_id,user_id)
);

create table if not exists public.channel_posts (
  id bigint generated by default as identity primary key,
  channel_id bigint not null references public.channels(id) on delete cascade,
  author_id bigint not null references public.users(id) on delete cascade,
  body text not null check (char_length(body) between 1 and 8000),
  parent_post_id bigint references public.channel_posts(id) on delete cascade,
  is_announcement boolean not null default false,
  created_at timestamptz not null default now()
);

create table if not exists public.call_logs (
  id bigint generated by default as identity primary key,
  caller_id bigint not null references public.users(id) on delete cascade,
  receiver_id bigint not null references public.users(id) on delete cascade,
  mode text not null check (mode in ('audio','video')),
  status text not null default 'started' check (status in ('started','answered','rejected','missed','ended')),
  started_at timestamptz not null default now(),
  ended_at timestamptz
);

create table if not exists public.ai_conversations (
  id bigint generated by default as identity primary key,
  user_id bigint not null references public.users(id) on delete cascade,
  title text not null default 'New AI conversation',
  assistant_type text not null default 'general',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.ai_messages (
  id bigint generated by default as identity primary key,
  conversation_id bigint not null references public.ai_conversations(id) on delete cascade,
  role text not null check (role in ('user','assistant')),
  content text not null,
  created_at timestamptz not null default now()
);

create index if not exists idx_group_members_user on public.group_members(user_id);
create index if not exists idx_group_messages_group_time on public.group_messages(group_id,created_at);
create index if not exists idx_channel_members_user on public.channel_members(user_id);
create index if not exists idx_channel_posts_channel_time on public.channel_posts(channel_id,created_at);
create index if not exists idx_call_logs_users_time on public.call_logs(caller_id,receiver_id,started_at);
create index if not exists idx_ai_conversations_user_time on public.ai_conversations(user_id,updated_at);

alter table public.groups enable row level security;
alter table public.group_members enable row level security;
alter table public.group_messages enable row level security;
alter table public.channels enable row level security;
alter table public.channel_members enable row level security;
alter table public.channel_posts enable row level security;
alter table public.call_logs enable row level security;
alter table public.ai_conversations enable row level security;
alter table public.ai_messages enable row level security;

-- The application server uses the Supabase service role and enforces access itself.
