-- CONNECTCHAT PRO 1.4.0 SOCIAL FEATURES MIGRATION
-- Run once in Supabase > SQL Editor before deploying version 1.4.0.
-- Safe to run again. It does not delete users, messages, or attachments.

alter table public.users
  add column if not exists last_seen_at timestamptz;

alter table public.messages
  add column if not exists delivered_at timestamptz;

alter table public.messages
  add column if not exists read_at timestamptz;

create table if not exists public.user_statuses (
  id bigint generated by default as identity primary key,
  user_id bigint not null references public.users(id) on delete cascade,
  kind text not null check (kind in ('text','image','video')),
  body text,
  file_url text,
  file_name text,
  mime_type text,
  created_at timestamptz not null default now(),
  expires_at timestamptz not null default (now() + interval '24 hours')
);

create table if not exists public.status_views (
  status_id bigint not null references public.user_statuses(id) on delete cascade,
  viewer_id bigint not null references public.users(id) on delete cascade,
  viewed_at timestamptz not null default now(),
  primary key (status_id, viewer_id)
);

create index if not exists user_statuses_active_idx
  on public.user_statuses(expires_at desc, created_at desc);

create index if not exists status_views_viewer_idx
  on public.status_views(viewer_id, status_id);

alter table public.user_statuses enable row level security;
alter table public.status_views enable row level security;

grant usage on schema public to service_role;
grant select, insert, update, delete
  on table public.users, public.messages, public.user_statuses, public.status_views
  to service_role;
grant usage, select on all sequences in schema public to service_role;

revoke all on table public.user_statuses, public.status_views
  from anon, authenticated;

select 'ConnectChat social migration completed' as result;
