create extension if not exists citext;

create table if not exists public.users (
  id bigint generated by default as identity primary key,
  username citext unique not null,
  password_hash text not null,
  avatar text,
  recovery_hash text unique,
  status text not null default 'pending',
  is_admin boolean not null default false,
  created_at timestamptz not null default now()
);

-- Upgrade an existing ConnectChat database without deleting users or messages.
-- Existing accounts remain approved; all accounts registered by the updated
-- server are explicitly created as pending.
alter table public.users add column if not exists status text not null default 'approved';
alter table public.users add column if not exists is_admin boolean not null default false;

do $$
begin
  if not exists (
    select 1 from pg_constraint
    where conname = 'users_status_check' and conrelid = 'public.users'::regclass
  ) then
    alter table public.users
      add constraint users_status_check check (status in ('pending','approved','blocked'));
  end if;
end $$;

-- The requested administrator. If this account already exists it becomes the
-- protected administrator immediately. This statement is safe to run again.
update public.users
set status = 'approved', is_admin = true
where lower(username::text) = lower('Abokanaan');

create table if not exists public.messages (
  id bigint generated by default as identity primary key,
  sender_id bigint not null references public.users(id) on delete cascade,
  receiver_id bigint not null references public.users(id) on delete cascade,
  kind text not null default 'text' check (kind in ('text','image','voice','file')),
  body text,
  file_url text,
  file_name text,
  mime_type text,
  created_at timestamptz not null default now()
);

create index if not exists messages_sender_receiver_idx
  on public.messages(sender_id, receiver_id, id desc);
create index if not exists messages_receiver_sender_idx
  on public.messages(receiver_id, sender_id, id desc);

-- Server-side sessions replace Express MemoryStore. Session identifiers are
-- hashed before storage, and browsers never receive direct table access.
create table if not exists public.app_sessions (
  sid text primary key,
  sess jsonb not null,
  expires_at timestamptz not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists app_sessions_expires_idx
  on public.app_sessions(expires_at);

alter table public.users enable row level security;
alter table public.messages enable row level security;
alter table public.app_sessions enable row level security;

-- The Node.js server uses the private service-role key and performs all
-- account and message authorization. No browser-access policies are required.
grant usage on schema public to service_role;
grant select, insert, update, delete on table public.app_sessions to service_role;
revoke all on table public.app_sessions from anon, authenticated;
