-- ConnectChat Pro v6 shared calculation sheets
-- Run this entire file once in Supabase SQL Editor before deploying v6.

create table if not exists public.calculation_sheets (
  id bigint generated by default as identity primary key,
  uploader_id bigint not null references public.users(id) on delete cascade,
  title text not null check (char_length(title) between 1 and 120),
  description text not null default '' check (char_length(description) <= 500),
  storage_path text not null unique,
  file_name text not null,
  mime_type text not null,
  file_size bigint not null default 0 check (file_size >= 0),
  access_scope text not null default 'all' check (access_scope in ('all','admins','selected')),
  created_at timestamptz not null default now()
);

create table if not exists public.calculation_sheet_access (
  sheet_id bigint not null references public.calculation_sheets(id) on delete cascade,
  user_id bigint not null references public.users(id) on delete cascade,
  created_at timestamptz not null default now(),
  primary key (sheet_id,user_id)
);

create index if not exists idx_calculation_sheets_created
  on public.calculation_sheets(created_at desc);

create index if not exists idx_calculation_sheets_uploader
  on public.calculation_sheets(uploader_id);

create index if not exists idx_calculation_sheet_access_user
  on public.calculation_sheet_access(user_id,sheet_id);

alter table public.calculation_sheets enable row level security;
alter table public.calculation_sheet_access enable row level security;

-- ConnectChat uses the Supabase service role. The application server enforces
-- approved-user access, uploader ownership, administrator-only files, selected
-- user sharing, and administrator deletion.
