-- ConnectChat Pro v6.7.3 group invitations
-- Safe to run more than once. Existing groups and members remain unchanged.

create table if not exists public.group_invitations (
  id bigint generated by default as identity primary key,
  group_id bigint not null references public.groups(id) on delete cascade,
  invitee_id bigint not null references public.users(id) on delete cascade,
  invited_by bigint not null references public.users(id) on delete cascade,
  status text not null default 'pending'
    check (status in ('pending','accepted','declined','cancelled')),
  created_at timestamptz not null default now(),
  responded_at timestamptz
);

create unique index if not exists group_invitations_one_pending_idx
  on public.group_invitations(group_id,invitee_id)
  where status = 'pending';

create index if not exists group_invitations_invitee_idx
  on public.group_invitations(invitee_id,status,created_at desc);

alter table public.group_invitations enable row level security;

-- The ConnectChat server uses the Supabase service role and enforces group
-- owner, administrator and invitee permissions in its API.
